// {"page":1,"results":,"total_pages":1000,"total_results":20000}

[
  {
    adult: false,
    backdrop_path: "/rfnmMYuZ6EKOBvQLp2wqP21v7sI.jpg",
    id: 774752,
    title: "The Guardians of the Galaxy Holiday Special",
    original_language: "en",
    original_title: "The Guardians of the Galaxy Holiday Special",
    overview:
      "On a mission to make Christmas unforgettable for Quill, the Guardians head to Earth in search of the perfect present.",
    poster_path: "/8dqXyslZ2hv49Oiob9UjlGSHSTR.jpg",
    media_type: "movie",
    genre_ids: [35, 878, 12],
    popularity: 196.643,
    release_date: "2022-11-25",
    video: false,
    vote_average: 7.403,
    vote_count: 238,
  },
  {
    adult: false,
    backdrop_path: "/qBx97wytqlyPqXATHqRgIVFxJRU.jpg",
    id: 436270,
    title: "Black Adam",
    original_language: "en",
    original_title: "Black Adam",
    overview:
      "Nearly 5,000 years after he was bestowed with the almighty powers of the Egyptian gods—and imprisoned just as quickly—Black Adam is freed from his earthly tomb, ready to unleash his unique form of justice on the modern world.",
    poster_path: "/pFlaoHTZeyNkG83vxsAJiGzfSsa.jpg",
    media_type: "movie",
    genre_ids: [28, 14, 878],
    popularity: 15075.276,
    release_date: "2022-10-19",
    video: false,
    vote_average: 7.26,
    vote_count: 1987,
  },
  {
    adult: false,
    backdrop_path: "/9DpB6wC1iY5jxLz91RT8tIIsXaf.jpg",
    id: 119051,
    name: "Wednesday",
    original_language: "en",
    original_name: "Wednesday",
    overview:
      "Wednesday Addams is sent to Nevermore Academy, a bizarre boarding school where she attempts to master her psychic powers, stop a monstrous killing spree of the town citizens, and solve the supernatural mystery that affected her family 25 years ago — all while navigating her new relationships.",
    poster_path: "/jeGtaMwGxPmQN5xM4ClnwPQcNQz.jpg",
    media_type: "tv",
    genre_ids: [10765, 9648, 35],
    popularity: 712.912,
    first_air_date: "2022-11-23",
    vote_average: 8.801,
    vote_count: 521,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/c1bz69r0v065TGFA5nqBiKzPDys.jpg",
    id: 830784,
    title: "Lyle, Lyle, Crocodile",
    original_language: "en",
    original_title: "Lyle, Lyle, Crocodile",
    overview:
      "When the Primm family moves to New York City, their young son Josh struggles to adapt to his new school and new friends. All of that changes when he discovers Lyle — a singing crocodile who loves baths, caviar and great music — living in the attic of his new home. But when Lyle’s existence is threatened by evil neighbor Mr. Grumps, the Primms must band together to show the world that family can come from the most unexpected places.",
    poster_path: "/irIS5Tn3TXjNi1R9BpWvGAN4CZ1.jpg",
    media_type: "movie",
    genre_ids: [35, 10751, 10402],
    popularity: 898.282,
    release_date: "2022-10-07",
    video: false,
    vote_average: 7.33,
    vote_count: 47,
  },
  {
    adult: false,
    backdrop_path: "/ajztm40qDPqMONaSJhQ2PaNe2Xd.jpg",
    id: 83867,
    name: "Star Wars: Andor",
    original_language: "en",
    original_name: "Star Wars: Andor",
    overview:
      "The tale of the burgeoning rebellion against the Empire and how people and planets became involved. In an era filled with danger, deception and intrigue, Cassian Andor embarks on the path that is destined to turn him into a rebel hero.",
    poster_path: "/59SVNwLfoMnZPPB6ukW6dlPxAdI.jpg",
    media_type: "tv",
    genre_ids: [10765, 10759, 10768],
    popularity: 623.145,
    first_air_date: "2022-09-21",
    vote_average: 8.119,
    vote_count: 349,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/s1xnjbOIQtwGObPnydTebp74G2c.jpg",
    id: 90669,
    name: "1899",
    original_language: "en",
    original_name: "1899",
    overview:
      "Passengers on an immigrant ship traveling to the new continent get caught in a mysterious riddle when they find a second vessel adrift on the open sea.",
    poster_path: "/8KGvYHQNOamON6ufQGjyhkiVn1V.jpg",
    media_type: "tv",
    genre_ids: [9648, 18],
    popularity: 2588.268,
    first_air_date: "2022-11-17",
    vote_average: 7.909,
    vote_count: 292,
    origin_country: ["DE"],
  },
  {
    adult: false,
    backdrop_path: "/kP5k4gA6yJiQCeN5FNcGwRtGDuq.jpg",
    id: 736918,
    title: "The Noel Diary",
    original_language: "en",
    original_title: "The Noel Diary",
    overview:
      "Cleaning out his childhood home at Christmas, a novelist meets a woman searching for her birth mother. Will an old diary unlock their pasts — and hearts?",
    poster_path: "/f6mMqxJfAD2Ao4sto7kOq6a7tWg.jpg",
    media_type: "movie",
    genre_ids: [10749, 35, 18],
    popularity: 102.078,
    release_date: "2022-11-24",
    video: false,
    vote_average: 6.851,
    vote_count: 67,
  },
  {
    adult: false,
    backdrop_path: "/xDMIl84Qo5Tsu62c9DGWhmPI67A.jpg",
    id: 505642,
    title: "Black Panther: Wakanda Forever",
    original_language: "en",
    original_title: "Black Panther: Wakanda Forever",
    overview:
      "Queen Ramonda, Shuri, M’Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers in the wake of King T’Challa’s death. As the Wakandans strive to embrace their next chapter, the heroes must band together with the help of War Dog Nakia and Everett Ross and forge a new path for the kingdom of Wakanda.",
    poster_path: "/sv1xJUazXeYqALzczSZ3O6nkH75.jpg",
    media_type: "movie",
    genre_ids: [28, 12, 878],
    popularity: 2506.822,
    release_date: "2022-11-09",
    video: false,
    vote_average: 7.516,
    vote_count: 1039,
  },
  {
    adult: false,
    backdrop_path: "/7zQJYV02yehWrQN6NjKsBorqUUS.jpg",
    id: 724495,
    title: "The Woman King",
    original_language: "en",
    original_title: "The Woman King",
    overview:
      "The story of the Agojie, the all-female unit of warriors who protected the African Kingdom of Dahomey in the 1800s with skills and a fierceness unlike anything the world has ever seen, and General Nanisca as she trains the next generation of recruits and readies them for battle against an enemy determined to destroy their way of life.",
    poster_path: "/438QXt1E3WJWb3PqNniK0tAE5c1.jpg",
    media_type: "movie",
    genre_ids: [28, 18, 36],
    popularity: 1139.123,
    release_date: "2022-09-15",
    video: false,
    vote_average: 7.82,
    vote_count: 484,
  },
  {
    adult: false,
    backdrop_path: "/o3mothJXDR9vLlZHpwyfFCycCNx.jpg",
    id: 668461,
    title: "Slumberland",
    original_language: "en",
    original_title: "Slumberland",
    overview:
      "A young girl discovers a secret map to the dreamworld of Slumberland, and with the help of an eccentric outlaw, she traverses dreams and flees nightmares, with the hope that she will be able to see her late father again.",
    poster_path: "/f18kgonrgr8YvEuvshExS4XBGL8.jpg",
    media_type: "movie",
    genre_ids: [10751, 14, 12, 18],
    popularity: 1204.536,
    release_date: "2022-11-09",
    video: false,
    vote_average: 7.944,
    vote_count: 251,
  },
  {
    adult: false,
    backdrop_path: "/dsWxCsAdsocMNQFbhe39ynAOhBa.jpg",
    id: 1049233,
    title: "Lesson Plan",
    original_language: "pl",
    original_title: "Plan lekcji",
    overview:
      "After a teacher dies, his best friend — a former cop — takes a job at the school where he worked to confront the gang he thinks was responsible.",
    poster_path: "/wawP3mOUeRBrAtnbPwWK5eFaMdV.jpg",
    media_type: "movie",
    genre_ids: [80, 53],
    popularity: 40.502,
    release_date: "2022-11-23",
    video: false,
    vote_average: 6.15,
    vote_count: 20,
  },
  {
    adult: false,
    backdrop_path: "/vtnMv6btdq9ipALbwhRmHnIWukV.jpg",
    id: 843543,
    title: "Meet Cute",
    original_language: "en",
    original_title: "Meet Cute",
    overview:
      "A wildly inventive deconstruction of the romantic comedy built around the question: What would you do if you could travel to your loved ones’ past, heal their traumas, fix their problems, and change them into the perfect partner?",
    poster_path: "/8NBlso3DuV3frqOzLZ4UYPMTqYu.jpg",
    media_type: "movie",
    genre_ids: [35, 10749, 878],
    popularity: 56.783,
    release_date: "2022-09-21",
    video: false,
    vote_average: 6.022,
    vote_count: 45,
  },
  {
    adult: false,
    backdrop_path: "/kpUre8wWSXn3D5RhrMttBZa6w1v.jpg",
    id: 338958,
    title: "Disenchanted",
    original_language: "en",
    original_title: "Disenchanted",
    overview:
      "Disillusioned with life in the city, feeling out of place in suburbia, and frustrated that her happily ever after hasn’t been so easy to find, Giselle turns to the magic of Andalasia for help. Accidentally transforming the entire town into a real-life fairy tale and placing her family’s future happiness in jeopardy, she must race against time to reverse the spell and determine what happily ever after truly means to her and her family.",
    poster_path: "/4x3pt6hoLblBeHebUa4OyiVXFiM.jpg",
    media_type: "movie",
    genre_ids: [35, 10751, 14],
    popularity: 3316.598,
    release_date: "2022-11-16",
    video: false,
    vote_average: 7.458,
    vote_count: 378,
  },
  {
    adult: false,
    backdrop_path: "/hUrdrIfLwxFjx8UjwlAg28PiMDN.jpg",
    id: 1006917,
    title: "The Lost Patient",
    original_language: "fr",
    original_title: "Le Patient",
    overview:
      "The 19 years old Thomas wakes up in a hospital after three years in a coma. He doesn't remember anything. The psychologist Anna tells him that his family has been murdered and that he is the only survivor of the massacre while his sister Laura is still missing.",
    poster_path: "/tHwGtD4zT0IhKdc2JQNxHAJFGWn.jpg",
    media_type: "movie",
    genre_ids: [53, 9648, 10770, 18],
    popularity: 7.346,
    release_date: "2022-10-21",
    video: false,
    vote_average: 5.712,
    vote_count: 26,
  },
  {
    adult: false,
    backdrop_path: "/fHDvGGPFry65ou79WLi6JsjCZrM.jpg",
    id: 632856,
    title: "Spirited",
    original_language: "en",
    original_title: "Spirited",
    overview:
      "Each Christmas Eve, the Ghost of Christmas Present selects one dark soul to be reformed by a visit from three spirits. But this season, he picked the wrong Scrooge. Clint Briggs turns the tables on his ghostly host until Present finds himself reexamining his own past, present and future.",
    poster_path: "/h3zAzTMs5EP3cKusOxFNGSFE1WI.jpg",
    media_type: "movie",
    genre_ids: [35],
    popularity: 579.018,
    release_date: "2022-11-10",
    video: false,
    vote_average: 7.384,
    vote_count: 134,
  },
  {
    adult: false,
    backdrop_path: "/pQQYGl6JzyUzzd6TxjkVah3H8wq.jpg",
    id: 821881,
    title: "The Swimmers",
    original_language: "en",
    original_title: "The Swimmers",
    overview:
      "From war-torn Syria to the 2016 Rio Olympics, two young sisters embark on a risky voyage, putting their hearts and their swimming skills to heroic use.",
    poster_path: "/7gAmA9hvblerOc6xwOjYQwAnpWe.jpg",
    media_type: "movie",
    genre_ids: [18, 36],
    popularity: 29.281,
    release_date: "2022-11-24",
    video: false,
    vote_average: 8.234,
    vote_count: 32,
  },
  {
    adult: false,
    backdrop_path: "/fLDo1GXZWuBpMRkrzITYzBufath.jpg",
    id: 987919,
    title: "A Christmas Mystery",
    original_language: "en",
    original_title: "A Christmas Mystery",
    overview:
      "When her best friend's father is falsely accused of stealing the town's prized jingle bells, a young amateur sleuth and her friends must find the real thief before Christmas.",
    poster_path: "/7ROhQeFIRCDadpIe4C7fVi5mV1Q.jpg",
    media_type: "movie",
    genre_ids: [10751, 35, 18, 14, 9648, 53],
    popularity: 139.485,
    release_date: "2022-11-24",
    video: false,
    vote_average: 7.5,
    vote_count: 5,
  },
  {
    adult: false,
    backdrop_path: "/giveZjQGE4Pn3kJvsTn7uHqLjZS.jpg",
    id: 615952,
    title: "Armageddon Time",
    original_language: "en",
    original_title: "Armageddon Time",
    overview:
      "In 1980, Queens, New York, a young Jewish boy befriends a rebellious African-American classmate to the disapproval of his privileged family and begins to reckon with growing up in a world of inequality and prejudice.",
    poster_path: "/2bVjSEaLsUxUZ4Dutz9qRF5zXyd.jpg",
    media_type: "movie",
    genre_ids: [18],
    popularity: 129.209,
    release_date: "2022-10-28",
    video: false,
    vote_average: 6.934,
    vote_count: 83,
  },
];
